name: road_sign_detection
channels:
- anaconda-fusion
- defaults
dependencies:
- bzip2=1.0.6=vc9_3
- click=6.7=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.11=py27_0
- flask=0.12.2=py27_0
- freetype=2.5.5=vc9_2
- functools32=3.2.3.2=py27_0
- icu=57.1=vc9_0
- itsdangerous=0.24=py27_0
- jinja2=2.9.6=py27_0
- jpeg=9b=vc9_0
- libpng=1.6.27=vc9_0
- libtiff=4.0.6=vc9_3
- markupsafe=0.23=py27_2
- matplotlib=2.0.2=np113py27_0
- mkl=2017.0.3=0
- networkx=1.11=py27_0
- numpy=1.13.0=py27_0
- olefile=0.44=py27_0
- openssl=1.0.2l=vc9_0
- pillow=4.1.1=py27_0
- pip=9.0.1=py27_1
- pyparsing=2.1.4=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=1
- python-dateutil=2.6.0=py27_0
- pytz=2017.2=py27_0
- pywavelets=0.5.2=np113py27_0
- qt=5.6.2=vc9_5
- scikit-image=0.13.0=np113py27_0
- scikit-learn=0.18.2=np113py27_0
- scipy=0.19.1=np113py27_0
- setuptools=27.2.0=py27_1
- sip=4.18=py27_0
- six=1.10.0=py27_0
- subprocess32=3.2.7=py27_0
- tk=8.5.18=vc9_0
- vs2008_runtime=9.00.30729.5054=0
- werkzeug=0.12.2=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=vc9_3
prefix: E:\dev\Anaconda3\envs\road_sign_detection

